/**
 * \file chansons.cpp
 * \brief definition de chansons
 * \author 
 */

#include "chansons.h"

ChansonMusique Chansons::mario = {
    66,
    { // https://gist.github.com/CodyJung/2315618
        {76, NoteMusicale::DoubleCroche}, {76, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::DoubleCroche}, {76, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::DoubleCroche}, {72, NoteMusicale::DoubleCroche},
        {76, NoteMusicale::DoubleCroche}, {20, NoteMusicale::DoubleCroche},
        {79, NoteMusicale::DoubleCroche}, {20, NoteMusicale::Noire},
        {67, NoteMusicale::DoubleCroche}, {20, NoteMusicale::Noire},

        {72, NoteMusicale::DoubleCroche}, {20, NoteMusicale::Croche},
        {67, NoteMusicale::DoubleCroche}, {20, NoteMusicale::Croche},
        {64, NoteMusicale::DoubleCroche}, {20, NoteMusicale::Croche},
        {69, NoteMusicale::DoubleCroche}, {20, NoteMusicale::DoubleCroche},
        {71, NoteMusicale::DoubleCroche}, {20, NoteMusicale::DoubleCroche},
        {70, NoteMusicale::DoubleCroche}, {69, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::DoubleCroche}, {67, NoteMusicale::DoubleCroche},
        {76, NoteMusicale::DoubleCroche}, {79, NoteMusicale::DoubleCroche},
        {81, NoteMusicale::DoubleCroche}, {20, NoteMusicale::DoubleCroche},
        {77, NoteMusicale::DoubleCroche}, {79, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::DoubleCroche}, {76, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::DoubleCroche}, {72, NoteMusicale::DoubleCroche},
        {74, NoteMusicale::DoubleCroche}, {71, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::Croche},
        
        {72, NoteMusicale::DoubleCroche}, {20, NoteMusicale::Croche},
        {67, NoteMusicale::DoubleCroche}, {20, NoteMusicale::Croche},
        {64, NoteMusicale::DoubleCroche}, {20, NoteMusicale::Croche},
        {69, NoteMusicale::DoubleCroche}, {20, NoteMusicale::DoubleCroche},
        {71, NoteMusicale::DoubleCroche}, {20, NoteMusicale::DoubleCroche},
        {70, NoteMusicale::DoubleCroche}, {69, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::DoubleCroche}, {67, NoteMusicale::DoubleCroche},
        {76, NoteMusicale::DoubleCroche}, {79, NoteMusicale::DoubleCroche},
        {81, NoteMusicale::DoubleCroche}, {20, NoteMusicale::DoubleCroche},
        {77, NoteMusicale::DoubleCroche}, {79, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::DoubleCroche}, {76, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::DoubleCroche}, {72, NoteMusicale::DoubleCroche},
        {74, NoteMusicale::DoubleCroche}, {71, NoteMusicale::DoubleCroche},
        {20, NoteMusicale::Croche}
    },
    Tempo::Vivace
};

ChansonMusique Chansons::starWarsMarcheImperiale = {
    43,
    {
        {G4, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {Ds4, NoteMusicale::DoubleCroche},
        {As4, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {Ds4, NoteMusicale::DoubleCroche},
        {As4, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {D5, NoteMusicale::DoubleCroche},
        {D5, NoteMusicale::DoubleCroche},
        {D5, NoteMusicale::DoubleCroche},
        {Ds5, NoteMusicale::DoubleCroche},
        {As4, NoteMusicale::DoubleCroche},
        {Fs4, NoteMusicale::DoubleCroche},
        {Ds4, NoteMusicale::DoubleCroche},
        {As4, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {G5, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {G5, NoteMusicale::DoubleCroche},
        {Fs5, NoteMusicale::DoubleCroche},
        {F5, NoteMusicale::DoubleCroche},
        {E5, NoteMusicale::DoubleCroche},
        {Ds5, NoteMusicale::DoubleCroche},
        {E5, NoteMusicale::DoubleCroche},
        {0, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {0, NoteMusicale::DoubleCroche},
        {Cs5, NoteMusicale::DoubleCroche},
        {C5, NoteMusicale::DoubleCroche},
        {B4, NoteMusicale::DoubleCroche},
        {As4, NoteMusicale::DoubleCroche},
        {A4, NoteMusicale::DoubleCroche},
        {As4, NoteMusicale::DoubleCroche},
        {0, NoteMusicale::DoubleCroche},
        {Ds4, NoteMusicale::DoubleCroche},
        {0, NoteMusicale::DoubleCroche},
        {Fs4, NoteMusicale::DoubleCroche},
        {Ds4, NoteMusicale::DoubleCroche},
        {As4, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche},
        {Ds4, NoteMusicale::DoubleCroche},
        {As4, NoteMusicale::DoubleCroche},
        {G4, NoteMusicale::DoubleCroche}
    },
    Tempo::Vivace
};

ChansonMusique Chansons::twentieth = {
    73,
    {
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {58, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {59, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {63, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {63, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {53, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {58, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {58, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {58, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {60, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {58, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {48, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {48, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {55, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {55, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {58, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {51, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {51, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {53, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {58, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {60, NoteMusicale::TripleCroche},
        {0, NoteMusicale::TripleCroche},
        {62, NoteMusicale::TripleCroche}
    },
    Tempo::Prestissimo
};
